# Generated by Django 3.2.5 on 2021-07-29 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="csv",
            old_name="file_name",
            new_name="file",
        ),
        migrations.RenameField(
            model_name="csv",
            old_name="uploaded",
            new_name="uploaded_at",
        ),
    ]
